### ISSUE TITLE
Private Key gets "Binding signature verification failed" on import attempt

### ISSUE THREAD

**Issue by asadowski** [google/end-to-end#337] opened 2015-08-27 18:37 UTC
### == PLEASE DONT PUT ANY KEYS HERE == ###
Can't put private key here. Other key pairs created w/MacGPG2 seem to import OK though, so kind of stumped.  Public key with 3 IDs imports fine. Additional ID is a Photo/JPG and is ignored. Private Key with 2 subkeys (RSA, ELG-E) will not import

**Debug instructions:**

1. Please build the extension and go to chrome-extension:// id>/prompt.html and try to encrypt, decrypt or import a key from there.

2. Note the error shown in red (if any)
**Key Binding Signature Verification Failed**

3. Open the JavaScript console (Tools -> JavaScript Console)

4. Copy the output from the console here.

`"CustomError: Binding signature verification failed. at e2e.openpgp.error.Error [as constructor]
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:2108:75) at new e2e.openpgp.error.SignatureError
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:2108:361) at e2e.openpgp.packet.Key.verifySignatureInternal_
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:4408:355) at e2e.openpgp.packet.Key.verifyBindingSignature_
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:4407:419) at null.<anonymous>
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:4405:158) at Function.e2e.ImmutableArray.forEach
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:3111:430) at e2e.openpgp.packet.Key.findNewestBindingSignature_
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:4405:109) at e2e.openpgp.packet.Key.verifySignatures
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:4404:236) at e2e.openpgp.block.TransferableKey.processSignatures
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:5099:285) at null.<anonymous>
(chrome-extension://okgecdkahgdmfcliiklafejolcocgcpe/launcher_binary.js:5244:329)"`

Have you tested if this key/message works in other implementations? (PGP Desktop, GnuPG, etc..)

Created key MacGPG2/GPGSuite. Have used it successfully there.  Successfully imported key pair into Mailvelope for Chrome.

**Comment by koto** [comment] 2015-08-27 19:51
Could you create a throwaway private key that does not import to reproduce the error? Or at least the key structure? (use `cat keyfile | gpg --list-packets`, and redact the output for the key material or the data you don't want to reveal).

**Comment by koto** [comment] 2015-08-27 19:53
Basically, we require all subkeys to have a key binding signature made by the main key packet. From the error messages it looks like one of the subkeys is missing such a signature.

**Comment by asadowski** [comment] 2015-08-28 00:46
Have tried to create a similar private key in the gui, but it imports fine. Created a keypair w/2 subkeys and 3 IDs and same options...

gpg --list-packets output (sanitized a bit... I'm not quite sure about what to keep out of it)

```
macbook:Desktop ajjones$ cat XXXXXXXX.asc | gpg --list-packets
:secret key packet:
	version 4, algo 1, created 1436452686, expires 0
	skey[0]: [4096 bits]
	skey[1]: [17 bits]
	iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: xxxxxxxxxxxxxxxx
	protect count: 19922944 (227)
	protect IV:  yy yy yy yy yy yy yy yy
	encrypted stuff follows
	keyid: XXXXXXXXXXXXXXXX
:user ID packet: "Adam Sadowski <adam@adamsadowski.com>"
:signature packet: algo 1, keyid XXXXXXXXXXXXXXXX
	version 4, created 1436453098, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 11 11
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 25 len 1 (primary user ID)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID XXXXXXXXXXXXXXXX)
	data: [4094 bits]
:user ID packet: "Adam Sadowski (Ad.am address) <adam@ad.am>"
:signature packet: algo 1, keyid XXXXXXXXXXXXXXXX
	version 4, created 1436453099, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 22 22
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID XXXXXXXXXXXXXXXX)
	data: [4092 bits]
:user ID packet: "Adam Sadowski (adam@sadowski.com Address) <adam@sadowski.com>"
:signature packet: algo 1, keyid XXXXXXXXXXXXXXXX
	version 4, created 1436453099, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 33 33
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID XXXXXXXXXXXXXXXX)
	data: [4096 bits]
:secret sub key packet:
	version 4, algo 1, created 1436452686, expires 0
	skey[0]: [4096 bits]
	skey[1]: [17 bits]
	iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: xxxxxxxxxxxxxxxx
	protect count: 19922944 (227)
	protect IV:  nn nn nn nn nn nn nn nn
	encrypted stuff follows
	keyid: gggggggggggggggg
:signature packet: algo 1, keyid XXXXXXXXXXXXXXXX
	version 4, created 1436454792, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 44 44
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h0m)
	subpkt 16 len 8 (issuer key ID XXXXXXXXXXXXXXXX)
	data: [4096 bits]
:secret sub key packet:
	version 4, algo 16, created 1436454737, expires 0
	skey[0]: [4096 bits]
	skey[1]: [3 bits]
	skey[2]: [4094 bits]
	iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: bbbbbbbbbbbbbbbb
	protect count: 19922944 (227)
	protect IV:  00 00 00 00 00 00 00 00 
	encrypted stuff follows
	keyid: eeeeeeeeeeeeeeee
:signature packet: algo 1, keyid XXXXXXXXXXXXXXXX
	version 4, created 1436454737, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 55 55
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 9 len 4 (key expires after 9y179d0h0m)
	subpkt 16 len 8 (issuer key ID XXXXXXXXXXXXXXXX)
	data: [4096 bits]
```

**Comment by koto** [comment] 2015-09-18 13:50
It's hard to tell without the private key material what's going on. You can compare the packet structure (e.g. with `pgpdump` or `gpg --list-packets`) to see any differences. Also `gpg --export-options export-clean` or `gpg --export-options export-minimal` might remove some unneeded signatures that cause the trouble.

**Comment by asadowski** [comment] 2015-09-21 01:03
export-clean and export minimal appear to generate same errors. I'm sure it's my key, but can't say much other than it works in Mailvelope and MacGPG. Happy to take this offline if it will help the project.  Don't want to clutter the thread with instructions to account for my lack of knowledge.....

**Comment by hakarune** [comment] 2015-10-19 02:42
My Keys get the same error. Created the keys in OpenKeychain android app, but not able to import them due a similar error. "cross-signature verification failed"

**Comment by koto** [comment] 2015-10-19 09:47
It might be https://github.com/open-keychain/open-keychain/issues/1353 (Keychain used to generate invalid signatures using too weak hash algorithm). I'll look if that's the same issue, thanks for posting the key.

**Comment by koto** [comment] 2015-10-19 10:16
No, it's not the case. @hakarune, we don't support signing subkeys (for E2E the primary key must be certifying other keys in the block, and you have a different, designated signing key packet). It's all good according to the spec, and some users prefer that, but we don't support it just yet.

**Comment by koto** [comment] 2015-10-20 08:00
Oops, I was wrong. hakarune@, it's a different issue, we don't truncate the hash correctly for DSA. I'll file and fix the issue. Thanks for helping us improve e2e!

**Comment by hakarune** [comment] 2015-10-23 07:58
Nice. I'm going to recompile and build tonight, thanks for the quick fix

**Comment by hakarune** [comment] 2015-10-27 03:15
Key import still fails after new build with said fixed

**Comment by koto** [comment] 2015-10-27 18:19
@hakarune, did you build the extension with the pull request merged? I only merged it now, as it was waiting in our review queue.

**Comment by asadowski** [comment] 2015-10-28 15:48
I realize this fix likely didn't address my issue (which I'm not able to diagnose) as my private key had no DSA subkeys. But for the sake of being thorough, I pulled the latest merge and rebuilt. Importing my private key yields the same error.

**Comment by sirdarckcat** [comment] 2016-04-25 15:37
@hakurane pgpdump was:
Old: Public Key Packet(tag 6)(525 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
Old: User ID Packet(tag 13)(34 bytes)
	User ID - Google Testing <testing@gmail.com>
Old: Signature Packet(tag 2)(560 bytes)
	Ver 4 - new
	Sig type - Positive certification of a User ID and Public Key packet(0x13).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: preferred symmetric algorithms(sub 11)(3 bytes)
		Sym alg - AES with 256-bit key(sym 9)
		Sym alg - AES with 192-bit key(sym 8)
		Sym alg - AES with 128-bit key(sym 7)
	Hashed Sub: preferred hash algorithms(sub 21)(1 bytes)
		Hash alg - SHA512(hash 10)
	Hashed Sub: preferred compression algorithms(sub 22)(1 bytes)
		Comp alg - ZIP <RFC1951>(comp 1)
	Hashed Sub: primary User ID(sub 25)(1 bytes)
		Primary - Yes
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: features(sub 30)(critical)(1 bytes)
		Flag - Modification detection (packets 18 and 19)
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to certify other keys
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Hash left 2 bytes - c2 fb 
	RSA m^d mod n(4095 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(525 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
Old: Signature Packet(tag 2)(1086 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to sign data
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Sub: embedded signature(sub 32)(critical)(540 bytes)
	Ver 4 - new
	Sig type - Primary Key Binding Signature(0x19).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0xA42E2EE93F585CC9
	Hash left 2 bytes - cb 27 
	RSA m^d mod n(4096 bits) - ...
		-> PKCS-1
	Hash left 2 bytes - 0d 5d 
	RSA m^d mod n(4095 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(525 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
Old: Signature Packet(tag 2)(543 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Hash left 2 bytes - b9 e7 
	RSA m^d mod n(4095 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(1037 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(8192 bits) - ...
	RSA e(17 bits) - ...
Old: Signature Packet(tag 2)(1598 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to sign data
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
		Flag - This key may be used for authentication
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Sub: embedded signature(sub 32)(critical)(1052 bytes)
	Ver 4 - new
	Sig type - Primary Key Binding Signature(0x19).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x8B6968C08096B88C
	Hash left 2 bytes - 1a 2f 
	RSA m^d mod n(8191 bits) - ...
		-> PKCS-1
	Hash left 2 bytes - e5 17 
	RSA m^d mod n(4095 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(2061 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - ElGamal Encrypt-Only(pub 16)
	ElGamal p(8192 bits) - ...
	ElGamal g(2 bits) - ...
	ElGamal y(8190 bits) - ...
Old: Signature Packet(tag 2)(543 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Hash left 2 bytes - 9e 91 
	RSA m^d mod n(4094 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(418 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - DSA Digital Signature Algorithm(pub 17)
	DSA p(1024 bits) - ...
	DSA q(160 bits) - ...
	DSA g(1023 bits) - ...
	DSA y(1021 bits) - ...
Old: Signature Packet(tag 2)(615 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to sign data
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Sub: embedded signature(sub 32)(critical)(70 bytes)
	Ver 4 - new
	Sig type - Primary Key Binding Signature(0x19).
	Pub alg - DSA Digital Signature Algorithm(pub 17)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x4F789CE3B58E3A10
	Hash left 2 bytes - 16 a4 
	DSA r(160 bits) - ...
	DSA s(159 bits) - ...
		-> hash(DSA q bits)
	Hash left 2 bytes - 04 ee 
	RSA m^d mod n(4094 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(147 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - Reserved for ECDSA(pub 19)
	Unknown public key(pub 19)
Old: Signature Packet(tag 2)(706 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to sign data
		Flag - This key may be used for authentication
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Sub: embedded signature(sub 32)(critical)(161 bytes)
	Ver 4 - new
	Sig type - Primary Key Binding Signature(0x19).
	Pub alg - Reserved for ECDSA(pub 19)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0xDE3E68BD73E2A878
	Hash left 2 bytes - 52 1d 
	Unknown signature(pub 19)
	Hash left 2 bytes - 04 eb 
	RSA m^d mod n(4094 bits) - ...
		-> PKCS-1
Old: Public Subkey Packet(tag 14)(151 bytes)
	Ver 4 - new
	Public key creation time - Mon Oct 19 04:47:04 CEST 2015
	Pub alg - Reserved for Elliptic Curve(pub 18)
	Unknown public key(pub 18)
Old: Signature Packet(tag 2)(543 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA512(hash 10)
	Hashed Sub: signature creation time(sub 2)(critical)(4 bytes)
		Time - Mon Oct 19 04:47:04 CEST 2015
	Hashed Sub: key flags(sub 27)(critical)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
	Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0x79CCD98D266307B8
	Hash left 2 bytes - 72 d6 
	RSA m^d mod n(4096 bits) - ...
		-> PKCS-1

**Comment by sirdarckcat** [comment] 2016-04-25 15:55
that key works for me on head, will add a test

**Comment by sirdarckcat** [comment] 2016-04-25 16:02
This is the gpg2 --list-packets for https://pgp.mit.edu/pks/lookup?op=get&search=0x19C091DC6990C445 which I think is the key mentioned in https://github.com/google/end-to-end/issues/337#issuecomment-135593307

```
# off=0 ctb=99 tag=6 hlen=3 plen=525
:public key packet:
	version 4, algo 1, created 1436452686, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 19C091DC6990C445
# off=528 ctb=b4 tag=13 hlen=2 plen=37
:user ID packet: "Adam Sadowski <adam@adamsadowski.com>"
# off=567 ctb=89 tag=2 hlen=3 plen=578
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436453098, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 61 8f
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 25 len 1 (primary user ID)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4094 bits]
# off=1148 ctb=b4 tag=13 hlen=2 plen=42
:user ID packet: "Adam Sadowski (Ad.am address) <adam@ad.am>"
# off=1192 ctb=89 tag=2 hlen=3 plen=575
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436453099, md5len 0, sigclass 0x13
	digest algo 8, begin of digest e5 5f
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4092 bits]
# off=1770 ctb=b4 tag=13 hlen=2 plen=61
:user ID packet: "Adam Sadowski (adam@sadowski.com Address) <adam@sadowski.com>"
# off=1833 ctb=89 tag=2 hlen=3 plen=575
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436453099, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 6d 9e
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4096 bits]
# off=2411 ctb=d1 tag=17 hlen=6 plen=9471 new-ctb
:attribute packet: [jpeg image of size 9449]
# off=11888 ctb=89 tag=2 hlen=3 plen=578
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436454819, md5len 0, sigclass 0x13
	digest algo 8, begin of digest d6 bf
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 9y178d0h6m)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 25 len 1 (primary user ID)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4096 bits]
# off=12469 ctb=b9 tag=14 hlen=3 plen=525
:public sub key packet:
	version 4, algo 1, created 1436452686, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 0FB5B5F103E6CFB5
# off=12997 ctb=89 tag=2 hlen=3 plen=549
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436454012, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 6d 49
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h22m)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4095 bits]
# off=13549 ctb=b9 tag=14 hlen=3 plen=1037
:public sub key packet:
	version 4, algo 16, created 1436454737, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [3 bits]
	pkey[2]: [4094 bits]
	keyid: 6EA83E41684CC2A2
# off=14589 ctb=89 tag=2 hlen=3 plen=549
:signature packet: algo 1, keyid 19C091DC6990C445
	version 4, created 1436454792, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 80 48
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 2 len 4 (sig created 2015-07-09)
	hashed subpkt 9 len 4 (key expires after 9y178d0h0m)
	subpkt 16 len 8 (issuer key ID 19C091DC6990C445)
	data: [4096 bits]

```

**Comment by sirdarckcat** [comment] 2016-04-25 16:04
the public key imports fine, so I guess we can't reproduce this :(

@asadowski plz let me know if this works for you on the latest version

**Closed by sirdarckcat** 2016-04-25 16:04 UTC

**Comment by asadowski** [comment] 2016-04-25 17:15
Public key always imported fine.

Rebuilt extension... still can't import private key :-(

**Comment by sirdarckcat** [comment] 2016-04-25 19:02
we need a sample key (please don't send us your personal private key).

the private key provided by hakurane works fine.

**Comment by sirdarckcat** [comment] 2016-04-25 19:02
in other words, we can't reproduce the bug =(

**Comment by asadowski** [comment] 2016-04-25 19:35
yes, I understand... unfortunately, I created a test key with the same characteristics and it imports OK... so I don't know what it is about my key that doesn't work... I can't reproduce the key that leads to the bug
