### ISSUE TITLE
Wrong backup code

### ISSUE THREAD

**Issue by Fastidious** [google/end-to-end#313] opened 2015-06-17 14:49 UTC
Just fetched it this morning, built the extension, imported my key.
![screen shot 2015-06-17 at 10 49 31 am](https://cloud.githubusercontent.com/assets/8352292/8210125/929b99c2-14de-11e5-92d8-69f545d8a995.png)

**Comment by koto** [comment] 2015-06-17 14:57
Duplicate of #302

**Closed by koto** 2015-06-17 14:57 UTC
