### ISSUE TITLE
gpg: key FFFFFFFF: secret key imported

### ISSUE THREAD

**Issue by NoSubstitute** [google/end-to-end#329] opened 2015-07-18 22:36 UTC
#214 still reproducable with GPG 2.1.6, which is said to support EC keys.
Public keys are imported, but secret keys are probably required to have a proper ID and also include at least one UID.

**Comment by koto** [comment] 2015-07-20 08:50
Duplicate of #326

**Closed by koto** 2015-07-20 08:50 UTC
